include:
  - board: seeeduino_xiao_ble
    shield: cornechon_central_dongle
  - board: nice_nano_v2
    shield: cornechon_central_dongle
  - board: nice_nano_v2
    shield: cornechon_central_left
  - board: nice_nano_v2
    shield: cornechon_peripheral_left
  - board: nice_nano_v2
    shield: cornechon_peripheral_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
